### ISSUE TITLE
Modified /dist when people install the project

### ISSUE THREAD

**Issue by afontcu** [prograhammer/vue-library-template#1]
Hi there! I've been using your template for a few days and I have a question.

When some of my colleagues clone the project I created using this template and they `npm install` it, they find that the `/dist` folder is already modified and ready to be staged. 

Why is that? Is `npm install` also building the files, so they are different from the ones that they already cloned from the repo?

Is this normal? Did I do something wrong with the config?

Thanks! :)

**Comment by prograhammer** [comment]
Sorry about getting back to you so late. Yeah it gets built after you run `npm install`. This is because the prepublish hook is called after you do an npm install or before an npm publish. This is set in the package.json: `"prepublish": "npm run build"`. 

The reason they are seeing the `/dist` folder ready to be staged is because I've purposely removed it from the .gitignore. This is because ideally you want Github to have the built files so the docs display online. It's also where npm looks so someone can do an import into their own project (however, I could have used .npmignore).

I found a few things that were a bit off and I've improved certain parts and made the README much much better (with explanation about how to use Github pages to show off the library/docs). I hope to push this up later today, so be on the look out!

**Comment by afontcu** [comment]
Thanks :) That obviously makes sense, although it feels weird to find some unstaged files right after just "installing" dependencies.

**Comment by prograhammer** [comment]
Yeah, I agree. I liked it for publishing, but the drawback was it would do this on npm install. So I'm going to remove it in next update (which is nearly finished and ready).

**Comment by afontcu** [comment]
Maybe switching to `prepublishOnly` hook would do the trick: 

> **prepublish**: Run BEFORE the package is packed and published, as well as on local npm install without any arguments. (See below)
**prepare**: Run both BEFORE the package is packed and published, and on local npm install without any arguments (See below). This is run AFTER prepublish, but BEFORE prepublishOnly.
**prepublishOnly**: Run BEFORE the package is prepared and packed, ONLY on npm publish. (See below.)

From [npm docs](https://docs.npmjs.com/misc/scripts)

**Comment by prograhammer** [comment]
^ Ahhh, was just about to look and see if there was something like this! Perfect! Thank you.

**Comment by prograhammer** [comment]
Updated!
